syntax = "proto3";

package category.v1;

import "google/protobuf/empty.proto";

// Сервис для работы с категориями
service CategoryService {
    // получение всех категорий
    rpc GetAllCategories (google.protobuf.Empty) returns (GetAllCategoriesResponse);
    
    // создание категории
    rpc CreateCategory (CreateCategoryRequest) returns (Category);
    
    // обновление категории
    rpc UpdateCategory (UpdateCategoryRequest) returns (Category);
    
    // удаление категории
    rpc DeleteCategory (DeleteCategoryRequest) returns (google.protobuf.Empty);
}

// Запросы
message CreateCategoryRequest {
    string title = 1;
    string slug = 2;
}

message UpdateCategoryRequest {
    string id = 1;
    string title = 2;
    string slug = 3;
}

message DeleteCategoryRequest {
    string id = 1;
}

// Ответы
message GetAllCategoriesResponse {
    repeated Category categories = 1;
}

message Category {
    string id = 1;
    string title = 2;
    string slug = 3;
}