syntax = "proto3";

package sector.v1;

service SectorService {
    // Создание сектора
    rpc CreateSector (CreateSectorRequest) returns (CreateSectorResponse);
    // Получение сектора по id
    rpc GetSector (GetSectorRequest) returns (GetSectorResponse);
    // Получение секторов для конкретной арены
    rpc ListSectorsByArena (ListSectorsRequest) returns (ListSectorsResponse);
    // Обновление сектора
    rpc UpdateSector (UpdateSectorRequest) returns (UpdateSectorResponse);
    // Удаление сектора
    rpc DeleteSector (DeleteSectorRequest) returns (DeleteSectorResponse);
}

message CreateSectorRequest {
    string name = 1;
    string arena_id = 2;
    repeated RowLayout layout = 3;
}

message CreateSectorResponse {
    Sector sector = 1;
}

message GetSectorRequest {
    string id = 1;
}

message GetSectorResponse {
    Sector sector = 1;
}

message ListSectorsRequest {
    string arena_id = 1;
}

message ListSectorsResponse {
    repeated Sector sectors = 1;
}

message UpdateSectorRequest {
    string id = 1;
    string name = 2;
    repeated RowLayout layout = 3;
}

message UpdateSectorResponse {
    Sector sector = 1;
}

message DeleteSectorRequest {
    string id = 1;
}

message DeleteSectorResponse {
    bool success = 1;
}

message Sector {
    string id = 1;
    string name = 2;
    string arena_id = 3;
}

message RowLayout {
    int32 row = 1;
    int32 columns = 2;
    string type = 3;
    int32 price = 4;
}